from enum import Enum

class IntentType(str, Enum):
    LOG_WORK = "LOG_WORK"
    LOG_HABIT = "LOG_HABIT"
    ADD_INBOX = "ADD_INBOX"
    SESSION_CONTROL = "SESSION_CONTROL"
    SYSTEM_CONFIG = "SYSTEM_CONFIG"
    UNDO = "UNDO"
    CHAT_OR_UNKNOWN = "CHAT_OR_UNKNOWN"
    ERROR = "ERROR"
    UNKNOWN_PROVIDER = "UNKNOWN_PROVIDER"
