from enum import Enum

class IntentType(str, Enum):
    LOG_WORK = "LOG_WORK"
    CREATE_ENTITIES = "CREATE_ENTITIES"
    ADD_INBOX = "ADD_INBOX"
    ADD_TASKS = "ADD_TASKS"
    SESSION_CONTROL = "SESSION_CONTROL"
    SYSTEM_CONFIG = "SYSTEM_CONFIG"
    CONFIG_REPORT = "CONFIG_REPORT"
    GENERATE_REPORT = "GENERATE_REPORT"
    UNDO = "UNDO"
    EDIT_ENTITIES = "EDIT_ENTITIES"
    CHAT_OR_UNKNOWN = "CHAT_OR_UNKNOWN"
    ERROR = "ERROR"
    UNKNOWN_PROVIDER = "UNKNOWN_PROVIDER"
